# Generated by Django 4.0.4 on 2022-04-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0002_delete_systemcontrol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mothership',
            table='mothership_mothership',
        ),
    ]
