# Generated by Django 4.0.4 on 2022-04-28 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mothership', '0003_alter_mothership_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mothership',
            table='mothership',
        ),
    ]
