# Generated by Django 4.0.4 on 2022-04-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemControl',
        ),
    ]
