# Generated by Django 4.0.4 on 2022-04-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ship', '0002_delete_systemcontrol'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ship',
            table='ship_ship',
        ),
    ]
