# Generated by Django 4.0.4 on 2022-04-28 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('ship_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='ship.ship')),
            ],
        ),
    ]
