# Generated by Django 4.0.4 on 2022-04-28 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0002_alter_crew_ship_assigned'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crew',
            table='crew_crew',
        ),
    ]
